### ISSUE TITLE
simbtype - what values do we want?

### ISSUE THREAD

**Issue by romanchyla** [adsabs/ADSMasterPipeline#20]
@ehenneken can you please verify if the following behaviour/data is what you need?

for bibcode: 1969A&A.....2..453T
we have this source data: "simbad_objects": ["1436813 OH*", "209386 MoC", "2361674 HII", "2363247 HII", "2419309 reg", "2518207 SNR", "2657860 SNR", "2738107 MoC", "2776865 Mi*", "31578 s*r", "54124 Rad", "810146 HII"]

and we'll generate the following:

```json

simbid":[1436813,
          209386,
          2361674,
          2363247,
          2419309,
          2518207,
          2657860,
          2738107,
          2776865,
          31578,
          54124,
          810146],
"simbtype":["OH*",
          "MoC",
          "HII",
          "HII",
          "reg",
          "SNR",
          "SNR",
          "MoC",
          "Mi*",
          "s*r",
          "Rad",
          "HII"],
        "simbad_object_facet_hier":["0/Star",
          "1/Star/1436813",
          "0/Other",
          "1/Other/209386",
          "0/HII Region",
          "1/HII Region/2361674",
          "0/HII Region",
          "1/HII Region/2363247",
          "0/Other",
          "1/Other/2419309",
          "0/Nebula",
          "1/Nebula/2518207",
          "0/Nebula",
          "1/Nebula/2657860",
          "0/Other",
          "1/Other/2738107",
          "0/Star",
          "1/Star/2776865",
          "0/Star",
          "1/Star/31578",
          "0/Other",
          "1/Other/54124",
          "0/HII Region",
          "1/HII Region/810146"],
```

the old solr index has different simbtypes:

```
"simbtype":["HII Region",
          "Nebula",
          "Other",
          "Star"],
```

Q1: do you want human-readable simbtypes (HII) or do you need the original type (HII Region)
Q2: the old solr only has 4 types - when there are 12 objects. Shouldn't each simbid has its own entry with type?

**Comment by aaccomazzi** [comment]
I think the new data is solr is what we want.  We are adopting SIMBAD's own taxonomy for types which means users will be able to search on them in conjunction with other parameters. 
The facets are more human readable than the types, but that's the way they are supposed to be.

The old solr only had a subset of the types and I believe it took a set() on them to make a unique list.  Having the complete list, with repetition I think it's a feature in that we may one day use leverage this via tf/idf for these fields.

So all and all I think this is what we want. 

I checked the correctness of the data btw as found in their record and it looks good: http://simbad.harvard.edu/simbad/sim-ref?bibcode=1969A%26A.....2..453T&simbo=on

**Comment by ehenneken** [comment]
I concur! Bumblebee uses `simbid` and `simbad_object_facet_hier` to populate the facet and in object searches. So, the above example should not interfere with how Bumblebee functions.
