### ISSUE TITLE
Incorrect values for `nedid`in Solr documents

### ISSUE THREAD

**Issue by ehenneken** [adsabs/ADSMasterPipeline#21]
For `2011A&A...526A.123R`, I see `"nedid":["NGC"]` and it should be `"nedid":["NGC 5128"]`. Is this the result of the following code in `adsmp/solr_updater.py`?
```
    for x in data.get('ned_objects', []):
        nid, ntype = x.split(' ', 1)
        nedid.append(nid)
        nedtype.append(map_ned_type(ntype))
        ned_object_facet_hier.extend(generate_hier_facet(map_ned_type(ntype), nid))
```

**Comment by spacemansteve** [comment]
as the nedids are read into postgres they look like they are quoted correctly:
data_pipeline=# select * from nonbibstaging.ned limit 10;
       bibcode       |              ned_objects              
---------------------+---------------------------------------
 1885AN....112..285E | {"MESSIER 031 G","SN 1885A SN"}
 1885AN....112..285H | {"MESSIER 031 G","SN 1885A SN"}
 1885AN....112..404B | {"MESSIER 031 G","SN 1885A SN"}
 1885AN....112..404W | {"MESSIER 031 G","SN 1885A SN"}
 1887AN....118..123F | {"MESSIER 031 G","SN 1885A SN"}
 1900SSCN....2.....R | {"MESSIER 031 G"}
 1912MNRAS..72..408R | {"NGC 0278 G"}

and the quotes remain after nonbib data is merged:
data_pipeline=# select ned_objects from nonbibstaging.rowviewm where bibcode='1885AN....112..285E';
           ned_objects           
---------------------------------
 {"MESSIER 031 G","SN 1885A SN"}

**Comment by ehenneken** [comment]
Thanks for checking! The search continues... :-)

**Comment by ehenneken** [comment]
So, @romanchyla given the findings above, something goes wrong when the Solr documents are populated with NED data

**Comment by ehenneken** [comment]
@romanchyla @spacemansteve I will update the creation of the column file `ned_objects.tab` so that the identifiers (second column) no longer contain spaces. This will bring the NED procedure much more in line with SIMBAD, with the one difference that NED identifiers are general alphanumeric strings, while the SIMBAD identifiers are just integers. I think this solution will take care of everything, but I'll leave this issue open until after the updated NED identifiers have been indexed and I've verified this.

**Comment by ehenneken** [comment]
The above work has been completed and I have updated the harvesting procedure that creates the Classic "column file" `ned_objects.tab` so that from now on the NED object identifiers should always have underscores instead of spaces. I'll double check after this weekend's Classic update to see that I'm telling the truth ;-)

**Comment by ehenneken** [comment]
All looks well... both the NED fields in Solr and the `ned_objects.tab` file!
