### ISSUE TITLE
Index to Solr without fulltext as last resort

### ISSUE THREAD

**Issue by spacemansteve** [adsabs/ADSMasterPipeline#40]
Once fulltext data for a bibcode has been received, master will not send a Solr record without fulltext populating the body field.  Before fulltext has been received master may send out a Solr records without the body field.  The most common reason Solr rejects a record is the contents of the body field.  We have decided if Solr ingest fails for an individual records fails it is worth trying it again without the body field.  This should still be reported as an error because the fulltext is an important part of the record.  By indexing without fulltext we at least get some data into Solr, which is better than nothing.

**Comment by romanchyla** [comment]
@spacemansteve  the last change introduced a bug, at line: 460 - the failed_bibcode is not initialized

this must result in a relatively high rate of reindexing erros and i'd expect it slows down processing

**Comment by spacemansteve** [comment]
PR sent to fix this.
